/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c2276f2f-da9d-4e92-93e0-b2e0a1cfc91d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Db0lrmpco",
    "aws_user_pools_web_client_id": "rak14ps1v6dlv5qo00m64v79s",
    "oauth": {}
};


export default awsmobile;
